In [19]:
import scipy.linalg as linalg
import numpy as np

In [55]:
a = np.array([[3/2, 1], [-1, 0]])

In [56]:
u, p = linalg.polar(a)

In [57]:
np.matmul(a,a.T)

array([[ 3.25, -1.5 ],
       [-1.5 ,  1.  ]])

In [58]:

np.matmul(a.T,a)

array([[3.25, 1.5 ],
       [1.5 , 1.  ]])

In [53]:
u

array([[0., 1.],
       [1., 0.]])

In [16]:
p

array([[1.7, 0.6],
       [0.6, 0.8]])

In [18]:
a * a

array([[2.25, 1.  ],
       [1.  , 0.  ]])